import { ApiProperty } from '@nestjs/swagger';

export const ApiPropertyRefusal = () =>
  ApiProperty({
    type: 'string',
    description: 'The refusal message generated by the model',
    example: 'I apologize, but I cannot help you with that.',
    required: false,
  });

export const ApiPropertyContent = () =>
  ApiProperty({
    type: 'string',
    description: 'The contents of the message',
    example: 'London is the capital of Great Britain.',
    required: false,
  });

export const ApiPropertyBytes = () =>
  ApiProperty({
    type: [Number],
    description:
      'A list of integers representing the UTF-8 bytes representation of the token',
    required: false,
    example: [213, 155, 123, 255, 1, 17],
  });

export const ApiPropertyToken = () =>
  ApiProperty({
    type: 'string',
    description: 'The token',
    example: 'the',
  });

export const ApiPropertyLogprob = () =>
  ApiProperty({
    type: 'number',
    description: 'The log probability of the token',
    required: false,
    example: 1.8966641426086426,
  });
